### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by axecopfire** [theClubhouse-Augusta/southern-dev#18]
Need a way to let people know what the conference agenda is.

**Comment by JIntrocaso** [comment]
Look at using Tockify for schedule.
[Tockify](https://tockify.com/)

**Comment by JIntrocaso** [comment]
Schedule and event pug templates have been completed. Needs some styling. Changes are in schedule page branch. Data is being fed from json file in gulp build process.

**Comment by JIntrocaso** [comment]
Added css grid to layout assistance and since @axecopfire just wants to turn me to the dark side of front end development. All current schedule changes are in data-refactor branch. schedule-page branch can be blown away I believe.
