### ISSUE TITLE
Email Subscribe Not Working

### ISSUE THREAD

**Issue by JIntrocaso** [theClubhouse-Augusta/southern-dev#19]
Need to allow users to stay up to date with conference info by signing up via email to an email list. Not sure where to keep the emails. Will probably look at either 3rd party (MailChimp, SendGrid) or saving in db somewhere.

**Comment by axecopfire** [comment]
How is the new mailchimp feature working? Can we close out this issue?

**Comment by axecopfire** [comment]
Marking close because we have updated site to use mailchimp
