### ISSUE TITLE
Social Media optimization

### ISSUE THREAD

**Issue by axecopfire** [theClubhouse-Augusta/southern-dev#44]
- Need cover image to show on social media posts
- Should have a Facebook event for the conf

**Comment by JIntrocaso** [comment]
I am looking into the Twitter Cards for the site and can create a FB page for the event as well. Who should the admins of the FB site be?

**Comment by axecopfire** [comment]
You and me as admins at least until we can get another volunteer.

**Comment by JIntrocaso** [comment]
Added FB page for conf and added event for the first annual conference date.
