### ISSUE TITLE
Enforce https for GitHub Pages hosting

### ISSUE THREAD

**Issue by imarrsh** [theClubhouse-Augusta/southern-dev#68]
Https connections are made pretty easy for GitHub pages - its good practice to secure connections, especially if collecting visitor info over the wire. [This guide is a good starting point](https://help.github.com/en/articles/securing-your-github-pages-site-with-https).

**Comment by axecopfire** [comment]
Added. Never saw this issue for some reason. Sorry about that. Tried before and was getting some weird certificate error, so stopped trying. But it should work now. Thanks for the heads up.

**Comment by imarrsh** [comment]
W00t - just now seeing this! No worries - we're all busy :)
